server:
  port: 8001
  address: 127.0.0.1

spring:
  application:
    name: payment


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    password: root
    username: root

mybatis:
  mapper-locations: classpath:main.mapper/*.xml
  type-aliases-package: main.main.entity


Eureka:
  client:
    register-with-eureka: true #向注册中心注册自己
    fetch-registry: true # 是否从Eureka抓取已有的注册信息，默认为true 集群必须为true才能配合ribbon使用负载均衡
    service-url:
      #注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true


